# Generated by Django 5.0.4 on 2024-04-28 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='proPic')),
                ('phone', models.CharField(max_length=20)),
                ('isStore', models.BooleanField(default=False)),
                ('storeName', models.CharField(blank=True, max_length=100, null=True)),
                ('storeDescription', models.TextField(blank=True, null=True)),
                ('storeAddress', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
