from django.urls import path
from store import views

urlpatterns = [
    path('', views.storeHome, name='storeHome'),
    path('addProduct', views.addProductPage, name='addProductPage'),
    path('products', views.productPage, name='productPage'),
    path('product/added', views.addProduct, name='addProduct'),
    path('product/<int:id>', views.editProductPage, name='editProductPage'),
    path('product/edited/<int:id>', views.editProduct, name='editProduct'),
    path('deleteProduct/<int:id>', views.deleteProduct, name='deleteProduct'),
    path('product/addToCart/<int:id>', views.addToCart, name='addToCart'),
    path('product/removeFromCart/<int:id>', views.removeFromCart, name='removeFromCart'),
    path('product/addToWishlist/<int:id>', views.addToWishlist, name='addToWishlist'),
    path('product/removeFromWishlist/<int:id>', views.removeFromWishlist, name='removeFromWishlist'),
    path('product/view/<int:id>', views.viewProduct, name='viewProduct'),
    path('product/review/<int:id>', views.addReview, name='addReview'),
    path('product/cart', views.cartItem, name='cartItem'),
    path('product/cart/increas/<int:id>', views.increaseCartQuantity, name='increaseCartQuantity'),
    path('product/cart/decrease/<int:id>', views.decreaseCartQuantity, name='decreaseCartQuantity'),
    path('product/order/<int:id>', views.orderProduct, name='orderProduct'),
    path('product/cart/orderall', views.orderAllCartProduct, name='orderAllCartProduct'),
    path('product/wishlist', views.wishListProduct, name='wishListProduct'),
    path('prodict/singleStore/<int:id>', views.singleStoreProduct, name='singleStoreProduct'),
    path('orders', views.storeOrder, name='storeOrder'),
    path('orderhistory', views.storeOrderHistory, name='storeOrderHistory'),
    path('orders/status/ready/<int:id>', views.orderStatusToReady, name='orderStatusToReady'),
    path('orders/status/pickedup/<int:id>', views.orderStatusToPickedUp, name='orderStatusToPickedUp'),
    path('orders/view', views.customerOrderView, name='customerOrderView'),
    path('prodict/discounted', views.discountedProducts , name='discountedProducts'),
    path('product/catagory/<int:id>', views.categoryProducts, name='categoryProducts'),
    path('orders/status/changeto/ready/<int:id>', views.makeStatusToReady, name='makeStatusToReady'),
    path('orders/status/changeto/pending/<int:id>', views.makeStatusToPending, name='makeStatusToPending'),
    path('orders/status/changeto/pickedup/<int:id>', views.makeStatusToPickedUp, name='makeStatusToPickedUp'),
    path('orders/status/changeto/cancel/<int:id>', views.makeStatusToCancle, name='makeStatusToCancle'),
    path('orders/status/Cancled/<int:id>', views.viewOrderCancelpageForIndivisualProduct, name='viewOrderCancelpageForIndivisualProduct'),
    path('order/cancle/<int:id>', views.viewOrderCancelpage, name='viewOrderCancelpage'),
    path('orders/status/Cancle/<int:id>', views.orderStatusToCancel, name='orderStatusToCancel'),
    path('order/history/view', views.customerOrderHistoryView, name='customerOrderHistoryView'),
    path('product/search', views.searchProducts, name='searchProducts'),
    path('stores', views.allTheStore, name='allTheStore'),
    path('profile/editpage/<int:id>', views.editProfilePage, name='editProfilePage'),
    path('profile/edit/<int:id>', views.editProfile, name='editProfile'),
    path('profile/password/<int:id>', views.changePasswordPage, name='changePasswordPage'),
    path('profile/password/change/<int:id>', views.changePassword, name='changePassword'),
]